<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vertex.Tax.Application\Vertex.Tax.Application.csproj" />
    <ProjectReference Include="..\Vertex.Tax.Domain\Vertex.Tax.Domain.csproj" />
    <ProjectReference Include="..\Vertex.Tax.Infrastructure\Vertex.Tax.Infrastructure.csproj" />
  </ItemGroup>

</Project>
